### ISSUE TITLE
Build script in PyPI source version uses default `jemalloc`

### ISSUE THREAD

**Issue by david-cortes** [Quantco/tabmat#205]
I see the build script for linux uses `jemalloc` with `disable-tls`:
[  "./autogen.sh --disable-cxx --with-jemalloc-prefix=local --with-install-suffix=local --disable-tls --disable-initial-exec-tls",](https://github.com/Quantco/tabmat/blob/ec8fcd237ed5f581fa61efe91733117366343d24/pyproject.toml#L73)

However, the source distribution in PyPI doesn't run that script when installing it through `pip`, relying instead on whatever `jemalloc` it finds when it tries to compile. If, for example, one tries to install `tabmat` from source through `pip`, it will later on fail to import, complaining about an error with `jemalloc`:
```
cannot allocate memory in static TLS block
```

**Comment by xhochy** [comment]
@david-cortes Is there a reason you are using the source distribution and not the binary wheels? Integrating `jemalloc` into the source build is probably too much work for us.

**Comment by david-cortes** [comment]
I was trying to install it in a platform for which there are no binary wheels.

**Comment by xhochy** [comment]
Is this a platform for which we could build wheels?

**Comment by david-cortes** [comment]
I was trying to install it in `aarch64` (v8) which is among the platforms supported by `xsimd`, so I guess it'd be good to build wheels for it too.
