### ISSUE TITLE
should we add pandas-style metadata to matrices?

### ISSUE THREAD

**Issue by MarcAntoineSchmidtQC** [Quantco/tabmat#21]
Currently, we view the matrices more as numpy arrays than pandas dataframe. Ideally, we want to be in the middle and view this as columnar data. Most importantly, storing the column names would be very helpful for many different workflows.

A non-exhaustive list of implementation ideas:

1. add this to the current implementation of Dense|Sparse|Split|Categorical-Matrix.
2. create a new class that will hold the matrix as an attribute and expose some pandas-style helper functions.

**Comment by MartinStancsicsQC** [comment]
#286  and #278 are steps in this direction
