### ISSUE TITLE
`-march` is not cross-platform

### ISSUE THREAD

**Issue by david-cortes** [Quantco/tabmat#223]
The setup script tries to set argument `-march=native` for non-ARM platforms:
https://github.com/Quantco/tabmat/blob/b97b0d400bedc00e5dbab97f5cbb8dd18905040f/setup.py#L110

But this argument is not accepted by GCC in platforms like PPC either. Instead, those platforms use argument `mcpu`, so one can specify it as `-mcpu=native` (at least for GCC in linux).

**Comment by jtilly** [comment]
We removed the `-march` flag entirely from `setup.py` in #228.
