### ISSUE TITLE
wheel build for aarch64 is incredibly slow

### ISSUE THREAD

**Issue by MarcAntoineSchmidtQC** [Quantco/tabmat#242]
Just realizing now that [this PR](https://github.com/Quantco/tabmat/pull/206) made the runtime of the wheel build step go from 20 minutes to ~2h.

See, e.g. [this CI run](https://github.com/Quantco/tabmat/actions/runs/4465780525).

**Comment by xhochy** [comment]
Yes, this is because the build isn't running natively but using emulation. In contrast to conda(-forge), cibuildwheel doesn't support crosscompilation.
